version: '3.8'

services:
  # nest-app:
  
  #   build: . 
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app    
  #   depends_on:
  #     - mariadb-db  

  mariadb-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0nflyd35p3545@PWD
      MYSQL_DATABASE: despesas
      MYSQL_USER: despeasas
      MYSQL_PASSWORD: 0nflyd35p3545@PWD
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-data:
